# Generated by Django 5.2 on 2025-04-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientreg',
            options={'verbose_name': 'Patient Registration', 'verbose_name_plural': 'Patients Registration'},
        ),
        migrations.AddField(
            model_name='patientreg',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientreg',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
