# Generated by Django 5.2 on 2025-04-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientreg',
            options={},
        ),
        migrations.RemoveField(
            model_name='patientreg',
            name='security_answer',
        ),
        migrations.RemoveField(
            model_name='patientreg',
            name='security_question',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
