# Generated by Django 5.2 on 2025-04-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0010_patientreg_captcha_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='captcha_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
