# Generated by Django 5.2 on 2025-04-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0011_doctorreg_captcha_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorreg',
            name='captcha_answer',
        ),
        migrations.RemoveField(
            model_name='patientreg',
            name='captcha_answer',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
