# Generated by Django 5.2 on 2025-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0012_remove_doctorreg_captcha_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='captcha_entered',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientreg',
            name='captcha_entered',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='mobilenumber',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
