# Generated by Django 5.2 on 2025-04-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0015_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorreg',
            name='captcha_entered',
        ),
        migrations.RemoveField(
            model_name='patientreg',
            name='captcha_entered',
        ),
        migrations.AddField(
            model_name='doctorreg',
            name='captcha_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientreg',
            name='captcha_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='mobilenumber',
            field=models.CharField(max_length=11),
        ),
    ]
