# Generated by Django 5.2 on 2025-04-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0017_remove_doctorreg_captcha_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreg',
            name='captcha_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientreg',
            name='captcha_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
